### ISSUE TITLE
warning when add applet to the panel in ubuntu 16.04

### ISSUE THREAD

**Issue by fossfreedom** [cybre/budgie-haste-applet#16]
```
(budgie-panel:3052): Gtk-WARNING **: Theme parsing error: <broken file>:1:0: Failed to import: The resource at '/com/github/cybre/budgie-haste-applet/style/style-318.css' does not exist
```

I see the above warning when I attempt to add the applet to the panel.

Thoughts?

**Comment by cybre** [comment]
Sorry, I removed 3.18 support because it has become too tedious to support two stylesheets.

**Comment by cybre** [comment]
I left a piece of code in there by accident, it's fixed in master.
The applet does not support GTK 3.18 as it has become too tedious to support two stylesheets.

**Comment by fossfreedom** [comment]
okey-dokey.  Thanks.
