### ISSUE TITLE
FR: GitHub Gists as provider

### ISSUE THREAD

**Issue by sixtyfive** [cybre/budgie-haste-applet#17]
It'd be awesome for us web developer types if GitHub Gists was available as a provider as well. Apparently there is an API for it (https://developer.github.com/v3/gists/) but I'm not sure if it would work with the distinction in "secret" and "public" gists that they have. Anyways, just a wish :smiley:

**Comment by cybre** [comment]
Fixed in #18 
Note: The applet will currently only work with Budgie from git because of the popover changes.

**Comment by cybre** [comment]
If you want to post gists to your GH account you can generate a personal access token (In GH settings) with the "gists" scope enabled and enter the token in the applet settings page.

**Comment by cybre** [comment]
Also, editing the haste will just upload it as a new gist. Maybe in the future, I will support proper editing and authentication directly from the applet.

**Comment by sixtyfive** [comment]
Wow, cool! To wait or to upgrade to unstable with Budgie from git? 😸
Thank you much Sir!
