### ISSUE TITLE
Indonesian Translation

### ISSUE THREAD

**Issue by yursan9** [cybre/budgie-haste-applet#21]
I have complete the translation of this applet in transifex. But, It's still fallback to en_US, when setting the language to Indonesia. It didn't happen to Budgie Screenshot Applet.
Budgie Screenshot:
![screenshot](http://i.imgur.com/Tr6d3dF.png)
Budgie Haste:
![haste](http://i.imgur.com/eUs9Nch.png)

**Comment by cybre** [comment]
Fixed in 41a6190
