### ISSUE TITLE
applet-info.h no such file or directory

### ISSUE THREAD

**Issue by IronJaeger** [cybre/budgie-haste-applet#3]
runing make ends up with a fatal error, here's the terminal output . Thanks:

ironjaeger@solus-cq58 ~/.haste-applet $ ./autogen.sh --prefix=/usr
/usr/share/aclocal/autotrace.m4:7: warning: underquoted definition of AM_PATH_AUTOTRACE
/usr/share/aclocal/autotrace.m4:7:   run info Automake 'Extending aclocal'
/usr/share/aclocal/autotrace.m4:7:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: linking file`build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
/usr/share/aclocal/autotrace.m4:7: warning: underquoted definition of AM_PATH_AUTOTRACE
/usr/share/aclocal/autotrace.m4:7:   run info Automake 'Extending aclocal'
/usr/share/aclocal/autotrace.m4:7:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3930.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for BUDGIE_PLUGIN... yes
checking for SOUP... yes
checking for valac... /usr/bin/valac
checking whether /usr/bin/valac is at least version 0.28... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating haste-applet/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

```
    haste-applet 1
    ========

    prefix:                 /usr
    libdir:                 ${exec_prefix}/lib
    sysconfdir:             /etc
    exec_prefix:            ${prefix}
    bindir:                 ${exec_prefix}/bin
    datarootdir:            ${prefix}/share

    compiler:               gcc
    cflags:                 -g -O1 
    ldflags:                
```

Making clean in haste-applet
make[1]: Entering directory '/home/ironjaeger/.haste-applet/haste-applet'
test -z "plugin-resources.h plugin-resources.c" || rm -f plugin-resources.h plugin-resources.c
test -z "libhasteapplet.la" || rm -f libhasteapplet.la
rm -f ./so_locations
rm -rf .libs _libs
rm -f _.o
rm -f *.lo
rm -f com.github.cybre.haste-applet.gschema.valid 
make[1]: Leaving directory '/home/ironjaeger/.haste-applet/haste-applet'
make[1]: Entering directory '/home/ironjaeger/.haste-applet'
rm -rf .libs _libs
rm -f *.lo
make[1]: Leaving directory '/home/ironjaeger/.haste-applet'
ironjaeger@solus-cq58 ~/.haste-applet $ make
make  all-recursive
make[1]: Entering directory '/home/ironjaeger/.haste-applet'
Making all in haste-applet
make[2]: Entering directory '/home/ironjaeger/.haste-applet/haste-applet'
glib-compile-resources --target=plugin-resources.h --sourcedir=../haste-applet --generate-header --c-name haste_applet ../haste-applet/plugin.gresource.xml
glib-compile-resources --target=plugin-resources.c --sourcedir=../haste-applet --generate-source --c-name haste_applet ../haste-applet/plugin.gresource.xml
make  all-am
make[3]: Entering directory '/home/ironjaeger/.haste-applet/haste-applet'
  CC       libhasteapplet_la-HasteApplet.lo
In file included from HasteApplet.c:17:0:
/usr/include/budgie-desktop/plugin.h:15:25: fatal error: applet-info.h: No such file or directory
compilation terminated.
Makefile:497: recipe for target 'libhasteapplet_la-HasteApplet.lo' failed
make[3]: *_\* [libhasteapplet_la-HasteApplet.lo] Error 1
make[3]: Leaving directory '/home/ironjaeger/.haste-applet/haste-applet'
Makefile:390: recipe for target 'all' failed
make[2]: **\* [all] Error 2
make[2]: Leaving directory '/home/ironjaeger/.haste-applet/haste-applet'
Makefile:402: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/ironjaeger/.haste-applet'
Makefile:333: recipe for target 'all' failed
make: **\* [all] Error 2
ironjaeger@solus-cq58 ~/.haste-applet $

**Comment by cybre** [comment]
That is a Budgie issue that has been fixed since the last release. You can either build Budgie from the repo or wait for the next release (Should happen soon).
