### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by christiankaindl** [cybre/budgie-haste-applet#6]
It would be really nice to be able to save short snippets and notes offline. Currently the applet does only work when you are connected to the internet which kinda sucks when you just want to keep notes :D

Regards
Grisu

**Comment by cybre** [comment]
Yeah, it makes sense having an option to save locally and upload later like in budgie-screenshot-applet.

**Comment by cybre** [comment]
This has been implemented in the latest release.
