### ISSUE TITLE
budgie-destkop required version

### ISSUE THREAD

**Issue by bilelmoussaoui** [cybre/budgie-haste-applet#9]
In configure.ac, the requested version of budgie-desktop is 2, is that really correct ? 
As the latest stable version available for me is 10.2.7
The same issue with screenshot-applet

**Comment by cybre** [comment]
It's correct.
2 is the current budgie-desktop pkgconfig version.
https://github.com/budgie-desktop/budgie-desktop/commit/4b8333fe3fbf5166b7e93555e2b0638313545236
